name: Windows
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: [ windows-2022 ]
    steps:
      - name: Hello
        run: echo "Hello!!"
